# Generated by Django 5.2.3 on 2025-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
